name: Tests

on:
    push:
        branches:
          [ main, '*.x' ]
    pull_request:
        branches:
          [ main, '*.x' ]

permissions:
    contents: read

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: [ 8.1, 8.2, 8.3 ]

        name: Tests on PHP ${{ matrix.php }} - ${{ matrix.stability }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, intl, pdo, sqlite, xdebug
                    tools: composer:v2, phpstan
                    coverage: none

            -   name: Install Dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

            -   name: Get Composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   name: Lint composer.json
                run: composer validate

            -   name: Run PHPStan
                run: composer lint

            -   name: Tests
                run: composer pest
